services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: [
      "migrate",
      "-path=/db/migrations",
      "-database=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable",
      "up"
    ]
    volumes:
      - ./db/migrations:/db/migrations