server_port: 8080
server_host: "0.0.0.0"
server_read_timeout: 10s
server_write_timeout: 10s
server_shutdown_timeout: 10s

tracker_port: 50051
tracker_host: "auth"

info_port: 50052
info_host: "info"

pg_ip: "postgres"
pg_port: 5432
pg_user: "postgres"
pg_password: "postgres"
pg_db: "postgres"
pg_timeout: 5s